apiVersion: v1
kind: ConfigMap
metadata:
  name: streamer-presets
  namespace: flussonic
data:
  listeners: |
    http 8181;
    http 8282;
    rtmp 1935;
    srt 9999;
  config_external_ingest: |
    config_external http://config-app.config-app-service.flussonic.svc.cluster.local:8086/ingest;
  config_external_transcoder: |
    config_external http://config-app.config-app-service.flussonic.svc.cluster.local:8086/transcoder;